### ISSUE TITLE
How to show the state names inside the above graph without using a data label plugin?

### ISSUE THREAD

**Issue by arunreghu** [sgratzl/chartjs-chart-geo#24]
https://codepen.io/sgratzl/pen/GRKLQBw
How to show the state names inside the above graph without using a data label plugin? I saw that you have used chartjs-plugin-datalabels plugin one one of  your graphs. I have multiple charts on my screen. When I install chartjs-plugin-datalabels plugin it will cause errors.How to do that state name inside a graph without plugin? Is there any default option?
Please take a look on the attached image i need something like that
![Screenshot from 2020-07-08 12-27-14](https://user-images.githubusercontent.com/20110524/86888480-db8bc400-c117-11ea-832b-9ddf3650657d.png)

**Comment by sgratzl** [comment]
No, there is no integrated way to render labels without the plugin. Since, the plugin exists and works well in my cases, I didn't implement an alternative solution. 

However, you can try to disable the plugin in your other charts. Chart.js allows you to en/disable plugins as part of the configuration https://www.chartjs.org/docs/latest/developers/plugins.html#disable-plugins

**Comment by arunreghu** [comment]
Can we use chartjs-plugin-labels(https://www.npmjs.com/package/chartjs-plugin-labels) instead of chartjs-plugin-datalabels (https://www.npmjs.com/package/chartjs-plugin-datalabels) 
Because "chartjs-plugin-datalabels"  requires Chart.js 2.7.0 or later. If i change chart js version it will affect my other other charts plugins.

**Comment by sgratzl** [comment]
I don't know this plugin and cannot say whether it would work or not.
