### ISSUE TITLE
Legend & quantize step

### ISSUE THREAD

**Issue by elvince** [sgratzl/chartjs-chart-geo#30]
Hi,

I can't get how the max value of the values is calculated for the legend:

I have value between 0 and 71 with a quantitize of 4, so I expect the steps to be 18 or at worst 20 but I get 25.. O_o

If I can't parametrized it, how can I override the function that calculate the min/max value? I tried to extend the scale function to provide my personal whole value without any effect.

How can I draw all the step value in the legend? Should I set its with higher?

Last question, why have you set up a 1000 const value for the the FitWidth function? why did you choose this value?

Thanks,

**Comment by elvince** [comment]
I found in the closed question #21 that we can set the "ticks" inside colorscale to manage the min/max/stepsize value.

**Comment by sgratzl** [comment]
yes color scale is just a regular chart.js scale, So it supports all the regular tick options but also inherits its limitations.

**Comment by sgratzl** [comment]
> I have value between 0 and 71 with a quantitize of 4, so I expect the steps to be 18 or at worst 20 but I get 25.. O_o
> 
> If I can't parametrized it, how can I override the function that calculate the min/max value? I tried to extend the scale function to provide my personal whole value without any effect.
> 
> How can I draw all the step value in the legend? Should I set its with higher?

see chart.js tick configuration, this plugin is not computing any of that by its own


> Last question, why have you set up a 1000 const value for the the FitWidth function? why did you choose this value?

a feature of this plugin is to automatically fit the outline to the canvas. In order to avoid recalculating the scale on each draw / resize, I first compute fit it into a unified scale (in this case a width of 1000pixels) and the manually scale it to the actual canvas width. 

related code: https://github.com/sgratzl/chartjs-chart-geo/blob/cfc2d423c3bbbdd72c011f2974792c4d22520272/src/scales/projection.js#L60-L104

**Comment by shubhayu222** [comment]
Facing this problem when I applied the equirectangular projection. I wanted ticks as integer but getting as float.
`        scales: {
          projection: {
            axis: 'x',
            projection: 'equirectangular', 
          },
          ColorScale: {
            axis: 'x',
            ticks: {
              precision: 0
            },
          }
        }`
