### ISSUE TITLE
Is there any way to pass the origin value to the color interpolation method?

### ISSUE THREAD

**Issue by amzrk2** [sgratzl/chartjs-chart-geo#50]
Hi,

I'm new to chartjs so I'm not sure if this is related to the scale settings of chartjs itself.

About the color scales in https://github.com/sgratzl/chartjs-chart-geo/blob/main/src/scales/color.ts#L187, by default when the value reaches the `interpolate()` function at `color.ts#L200` it passes through the `_getNormalizedValue()` function, so a set of `[1, 2]` becomes `[0, 1]`.

Is there a way to make the value go directly to the A function without normalizing it?

**Comment by sgratzl** [comment]
the color interpolation is actually just a way how the background color is computed. 

if you take a look at https://github.com/sgratzl/chartjs-chart-geo/blob/ba231a43acd96f4eaf789584bf908ffb6830e456/src/controllers/choropleth.ts#L112-L118

you see that it configures itself to have a customized background color which uses the controllers color function to resolve to its color.

Thus, if you specify an own `backgroundColor` function in your spec you have access to your data and return whatever color your like. 

However, you loose the ability for the automatic color legend, since it relies on the color scale. If it is just about defining what are the minimum / maximum value before the normalization you can configure the color scale domain similar to configuring the min/max in a bar chart scale.

**Comment by amzrk2** [comment]
As I am not using the color legend, I tried to wrap the default background function with my own which works great.

Thanks for the explanation!
