### ISSUE TITLE
Tooltip positioning for Mercator Projection

### ISSUE THREAD

**Issue by kazoompa** [sgratzl/chartjs-chart-geo#52]
Hi,

I was wondering if you had any idea on how to control the tooltip positioning for Mercator projection. Currently, the tooltip for USA is placed, I guess, at the center of a rectangle and therefore a little off the main polygon. See example below:

![image](https://user-images.githubusercontent.com/2814716/110127336-83cf5680-7d93-11eb-94e4-1aa1e7675d79.png)

Appreciate your feedback.

**Comment by sgratzl** [comment]
atm the center point is computing using the d3-geo path `centroid` function, see also 

https://github.com/sgratzl/chartjs-chart-geo/blob/ba231a43acd96f4eaf789584bf908ffb6830e456/src/elements/geoFeature.ts#L84-L95. Since in your case Alaska is so far out, it will move the center towards the middle of both.
