### ISSUE TITLE
check compatibility with v3.0

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/chartjs-chart-geo#6]
see PR: https://github.com/chartjs/Chart.js/pull/6722 which removes all the `updateElement` functions

**Comment by benmccann** [comment]
There's a number of changes upcoming in 3.0 

For example, you will not need any of the following lines in `updateElement` anymore:
```
    point._xScale = this.getScaleForId(meta.xAxisID);
    point._yScale = this.getScaleForId(meta.yAxisID);
    point._datasetIndex = this.index;
    point._index = index;
```

Also, one change you might consider making now is to remove the call to `superClass.updateElement.apply(this, arguments);` since it's a no-op.

I imagine that having `updateElements` instead of `updateElement` won't be harder and you'll actually end up with less code thanks to the improvements in 3.0

Compare `updateElements` in `master`: https://github.com/chartjs/Chart.js/blob/master/src/controllers/controller.bubble.js#L123

To `updateElement` in 2.9: https://github.com/chartjs/Chart.js/blob/2.9/src/controllers/controller.bubble.js#L83

**Comment by sgratzl** [comment]
see sgratzl/chartjs3 branch
